// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqksmhkoktjyllylttqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa3NtaGtva3RqeWxseWx0dHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjExMDgsImV4cCI6MjA3MTUzNzEwOH0.a4zgaGw8TtEihJlHkjPv2Vtz7NTrigzq2uwrwa0tzxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});